#!/usr/bin/env bun
/**
 * Render the Homebrew formula for loop from a release's SHA256SUMS.
 *
 * Usage:
 *     bun .github/scripts/render-formula.ts <version> <sha256sums-path> <output-path>
 *
 * Reads the aggregated SHA256SUMS (one "<sha>  loop-<target>.tar.gz" line per
 * asset) and writes a complete Formula/loop.rb. Each platform block is emitted
 * only if its tarball is present in SHA256SUMS, so Intel-mac support appears
 * automatically once the release includes loop-darwin-x64.tar.gz.
 *
 * Invoked by the update-homebrew-tap job in release.yml — keep the output in sync
 * with the bootstrap formula committed to notshekhar/homebrew-tap.
 */

// `\#{version}` is the literal Ruby interpolation, escaped so the template
// literal leaves it alone.
const url = (target: string) =>
    `https://github.com/notshekhar/loop/releases/download/v#{version}/loop-${target}.tar.gz`;

function main(): number {
    const args = Bun.argv.slice(2);
    if (args.length !== 3) {
        console.error("usage: render-formula.ts <version> <sha256sums> <output>");
        return 2;
    }
    const [version, sumsPath, outPath] = args as [string, string, string];

    const sums: Record<string, string> = {};
    const text = require("node:fs").readFileSync(sumsPath, "utf8") as string;
    for (const raw of text.split("\n")) {
        const line = raw.trim();
        if (!line) continue;
        const [sha, fname] = line.split(/\s+/);
        if (!sha || !fname) continue;
        // The desktop app's linux archives are also loop-*.tar.gz, and a
        // bare (.+) happily reads them as CLI targets named
        // "desktop-linux-x64" — inventing formula entries for binaries that
        // are Electron bundles, not the CLI Homebrew installs.
        const m = /^loop-(?!desktop-)(.+)\.tar\.gz$/.exec(fname);
        if (m) sums[m[1]!] = sha;
    }

    if (!("darwin-arm64" in sums)) {
        console.error("SHA256SUMS missing darwin-arm64 — refusing to render a broken formula");
        return 1;
    }

    const arch = (label: string, target: string) =>
        `    ${label} do\n` + `      url "${url(target)}"\n` + `      sha256 "${sums[target]}"\n` + `    end`;

    const mac = [arch("on_arm", "darwin-arm64")];
    if ("darwin-x64" in sums) {
        mac.push(arch("on_intel", "darwin-x64"));
    } else {
        // No prebuilt Intel-mac binary in this release (darwin-x64 isn't in the
        // CI matrix). Fail the install with a clear pointer rather than letting
        // Homebrew emit a confusing "no available formula" error. odie inside an
        // on_intel block runs only when evaluated on an Intel mac.
        mac.push(
            "    on_intel do\n" +
                "      odie <<~EOS\n" +
                "        loop has no prebuilt Intel-mac (x86_64) binary yet.\n" +
                "        Install it directly instead:\n" +
                "          curl -fsSL https://raw.githubusercontent.com/notshekhar/loop/main/install.sh | bash\n" +
                "      EOS\n" +
                "    end",
        );
    }

    const linux: string[] = [];
    if ("linux-arm64" in sums) linux.push(arch("on_arm", "linux-arm64"));
    if ("linux-x64" in sums) linux.push(arch("on_intel", "linux-x64"));

    const formula = `# typed: false
# frozen_string_literal: true

# loop — terminal coding agent. Multi-provider, fast, native TUI.
#
# AUTO-GENERATED by the update-homebrew-tap job in notshekhar/loop's release.yml
# (.github/scripts/render-formula.ts). Do not hand-edit — the next tag overwrites
# any changes to version/sha256. Edit the render script instead.
class Loop < Formula
  desc "Terminal coding agent — multi-provider, fast, native TUI"
  homepage "https://github.com/notshekhar/loop"
  version "${version}"
  license "MIT"

  on_macos do
${mac.join("\n")}
  end

  on_linux do
${linux.join("\n")}
  end

  def install
    # Tarball layout is <target>/{loop,package.json}; Homebrew chdirs into the
    # sole top-level dir. The binary reads its sidecar package.json via
    # dirname(execPath), so keep both together in libexec and symlink onto PATH
    # (execPath resolves through the symlink).
    libexec.install "loop", "package.json"
    bin.install_symlink libexec/"loop"
    bin.install_symlink libexec/"loop" => "agent"
  end

  test do
    assert_match version.to_s, shell_output("\#{bin}/loop --version")
  end
end
`;

    require("node:fs").writeFileSync(outPath, formula);
    console.log(formula);
    return 0;
}

process.exit(main());
