#!/usr/bin/env bun
/**
 * Regenerate `sounds-blob.ts` — the seven notification chimes, gzipped and
 * base64'd into a TS constant.
 *
 * Why embed them at all: `bun build --compile` does not carry loose sibling
 * files into the binary, and an asset import (`with { type: "file" }`) does not
 * survive loop's two-stage build — core is bundled to dist/index.js first,
 * which emits the asset next to it, and the later --compile of the CLI does not
 * pick it up. The same trap the Lua wasm hit: the shipped binary looks for a
 * path that exists only on the build machine. Bytes in a module survive both
 * stages, so that is what ships.
 *
 * Gzip earns its place here — AAC is already compressed, but these cues are
 * short and mostly quiet tails, so they still shrink by about two thirds
 * (39.4 KB raw -> 13.2 KB) before base64 inflates them again.
 *
 * Run after changing any asset:
 *   bun packages/core/src/notifications/scripts/generate-sounds.ts
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const here = import.meta.dir;
const assetsDir = join(here, "..", "assets");
const out = join(here, "..", "sounds-blob.ts");

/** The cue order is the enum's order, so the generated file reads predictably. */
const CUES = ["success", "error", "bloom", "press", "click", "release", "toggle"] as const;

const files = readdirSync(assetsDir);
const entries: string[] = [];
let raw = 0;
let packed = 0;

for (const cue of CUES) {
    const name = files.find((f) => f.replace(/\.[^.]+$/, "") === cue);
    if (!name) throw new Error(`no asset for cue "${cue}" in ${assetsDir}`);
    const bytes = readFileSync(join(assetsDir, name));
    const gz = Bun.gzipSync(bytes);
    const b64 = Buffer.from(gz).toString("base64");
    raw += bytes.length;
    packed += gz.length;
    // The extension travels with the bytes: afplay picks its decoder from the
    // file name, and `click` is a CAF where the rest are M4A.
    entries.push(
        `    // ${name} — ${bytes.length} B raw, ${gz.length} B gzipped\n` +
            `    ${cue}: { ext: ${JSON.stringify(name.slice(name.lastIndexOf(".")))}, gz: "${b64}" },`,
    );
}

const header = `// GENERATED by scripts/generate-sounds.ts — do not edit by hand.
//
// The seven interface chimes, gzipped then base64'd. Derived from cuelume's
// MIT-licensed sound recipes by Daniel Belyi; see THIRD_PARTY_NOTICES.md.
// ${raw} B raw -> ${packed} B gzipped -> ${Math.round((packed * 4) / 3)} base64 chars.

export interface EmbeddedCue {
    /** File extension, including the dot — afplay picks its decoder from it. */
    ext: string;
    /** gzip(bytes), base64'd. */
    gz: string;
}

export const EMBEDDED_CUES = {
`;

writeFileSync(out, header + entries.join("\n") + "\n} as const satisfies Record<string, EmbeddedCue>;\n");
console.log(`wrote ${out}`);
console.log(`${raw} B raw -> ${packed} B gzipped`);
